### ISSUE TITLE
課題_0717

### ISSUE THREAD

**Issue by Takamura-000** [Takamura-000/my-first-blog#1]
- [ ] デプロイが完了したら報告する。
- [ ] デプロイ完了後のアプリのURLを伝える。
- [ ] チュートリアル「Django URL」の章以降から，プルリクエストを作成する。
  - `git checkout -b branchname` から始める。

**Comment by technicakidz** [comment]
MEMO: 課題_0731 として継続課題にします．

**Comment by technicakidz** [comment]
質問するときに考えるべき項目とは？
- ゴールはなにか(どんな状態になればよいか)
- 現状はどんな状態か(リポジトリURLや関係コード)
- 調べたこと
- 試したこと(実行コマンド, 修正した箇所)
- 結果(エラーメッセージ)

**Comment by technicakidz** [comment]
デプロイ問題(issue で話した)は別サービスで代替する方がよいという結論になったため，クローズします．
