### ISSUE TITLE
課題_0809

### ISSUE THREAD

**Issue by technicakidz** [Takamura-000/my-first-blog#3]
### TODO
- [ ] チュートリアル [Djangoテンプレート](https://tutorial.djangogirls.org/ja/django_templates/) の章まで
- [ ] (可能であれば) ブランチを作成してデプロイの章以降の変更をPRにする
- [ ] ポートフォリオのためのアイデアを考える(今あるもの，学習してきたことでできそうなこと？)
- [ ] streamlit の使い方を調べてくる

**Comment by technicakidz** [comment]
8/17のレッスンでお話しすること
https://logmi.jp/tech/articles/326156

**Comment by technicakidz** [comment]
メモ: 上記課題内容は 0817 以降も継続．

**Comment by technicakidz** [comment]
8/28
レッスンで課題の細かい進捗が確認できなかったので，こちらのコメントでまとめてください．
次回レッスンの前日までにやったことを記載してください．


```
### やったこと
(URLなど)

### わかったこと
- URLの設定方法

### わからなかった(自分の言葉で説明する自信がない)こと
- デプロイの方法
```

**Comment by Takamura-000** [comment]
### やったこと

・HTML　入門の章

### わかったこと

・head BODYの書き方

### わからなかった(自分の言葉で説明する自信がない)こと

なし

**Comment by technicakidz** [comment]
上記の進捗いかがでしょうか！

**Comment by technicakidz** [comment]
メモ: ここに書いた課題のタスクはチュートリアルHTML入門のみ着手した．
今はポートフォリオの充実を目指したいため，HTML/CSSをメインに進めたい．
